exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/asotille/add-trailing-comma
    rev: v2.2.3
    hooks:
      - id: add-trailing-comma

  # Autoformatter
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.7.0
    hooks:
      - id: autopep8
        args: [
          '--in-place',
          '--aggressive',
          '--aggressive',
          '--aggressive',
          '--max-line-length', '80',
          '--ignore', 'W503',
          '--jobs', '2',
          '--recursive', '.'
          ]

  # Linter
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        # W391 - Blank line at end of file
        # W503 - Binary operator line break, conflicts with W504
        args: ['--ignore=W391,W503']
        additional_dependencies: [flake8-isort]


# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
